/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include"main.h"

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);
void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);


uint32_t psp_of_tasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];

int main(void) {
	init_scheduler_stack(SCHED_STACK_START);

	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;

	init_tasks_stack();

	init_systick_timer(TICK_HZ);

	for(;;);
}

void task1_handler(void) {
	while(1) {
		printf("This is task1\n");
	}
}

void task2_handler(void) {
	while(1) {
		printf("This is task2\n");
	}
}

void task3_handler(void) {
	while(1) {
		printf("This is task3\n");
	}
}

void task4_handler(void) {
	while(1) {
		printf("This is task4\n");
	}
}

void init_systick_timer(uint32_t tick_hz) {
	uint32_t *pSRVR =  (uint32_t*) 0xE000E014;
	uint32_t *pSCSR = (uint32_t*) 0xE000E010;
	uint32_t count_value = (SYSTICK_TIMER_CLK/tick_hz) - 1;

	// clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	// load the value into SVR
	*pSRVR |= count_value;

	// do some settings
	*pSCSR |= (1 << 1); // Enable systick exception request
	*pSCSR |= (1 << 2); // Indicates the clock source as the processor clock

	// enable the systick
	*pSCSR |= (1 << 0); // enables the counter
}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile("MSR MSP,%0": : "r" (sched_top_of_stack) : );
	__asm volatile("BX LR");
}

void init_tasks_stack(void) {
	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++) {
		pPSP = (uint32_t*) psp_of_tasks[i];

		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x001000000

		pPSP--; // PC
		*pPSP = task_handlers[i];

		pPSP--; // LR
		*pPSP = 0xFFFFFFFD;

		for(int j = 0; j < 13; j++) {
			pPSP--;
			*pPSP = 0;
		}

		psp_of_tasks[i] = (uint32_t)pPSP;
	}
}

void SysTick_Handler(void) {
	printf("Inside systick handler\n");
}
