/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>

int main(void) {

	// 1. Enable all configurable exceptions like usage fault, mem manage fault and bus fault

	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); // mem manage
	*pSHCSR |= (1 << 17); // bus fault
	*pSHCSR |= (1 << 18); // usage fault

	// 3. lets force the processor to execute some undefined instruction
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFF;

	void (*some_address) (void);

	some_address = (void*)(pSRAM);

	some_address();
	// 4. Analyze the fault

	for(;;);
}

// 2. implement the fault handlers
void HardFault_Hander(void) {
	printf("exception : Hardfault");
	while(1);
}

void MemManage_Handler(void) {
	printf("exception : MemManagefault");
	while(1);
}

void BusFault_Handler(void) {
	printf("exception : Busfault");
	while(1);
}

void UsageFault_Handler(void) {
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("exception : Usagefault");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF);
	while(1);
}

