/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>

int fun_divide(int x, int y) {
	return x / y;
}

int main(void) {

	// 1. Enable all configurable exceptions like usage fault, mem manage fault and bus fault

	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); // mem manage
	*pSHCSR |= (1 << 17); // bus fault
	*pSHCSR |= (1 << 18); // usage fault

	// 2. enable divide by zero trap
	uint32_t *pCCR = (uint32_t*) 0xE000ED14;
	*pCCR |= (1 << 4);

	// 3. atempt to divide by zero
	fun_divide(10, 0);

	for(;;);
}

// 2. implement the fault handlers
void HardFault_Hander(void) {
	printf("exception : Hardfault");
	while(1);
}

void MemManage_Handler(void) {
	printf("exception : MemManagefault");
	while(1);
}

void BusFault_Handler(void) {
	printf("exception : Busfault");
	while(1);
}

__attribute__ ((naked)) void UsageFault_Handler(void) {
	// here we extracted the value of MSP which happens to be the
	// base address of the stack frame(thread mode) which got saved during the exception entry
	// from the thread mode to handler mode
	__asm ("MRS r0,MSP");
	__asm ("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame) {

	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("exception : Usagefault");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF);
	printf("MSP = %p\n", pBaseStackFrame);
	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);
	while(1);
}

