/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"

int main(void) {

	RCC_AHB1ENR_t volatile *const pClkCtrlReg = (RCC_AHB1ENR_t *) 0x40023830;
	GPIOx_MODER volatile *const pPortDModeReg = (GPIOx_MODER *) 0x40020C00;
	GPIOx_ODR volatile *const pPortDOutReg = (GPIOx_ODR *) 0x40020C14;


	pClkCtrlReg->gpiod_en = 1;
	pPortDModeReg->pin_12 = 1;

	for(;;) {
		pPortDOutReg->pin_12 = 1;

		// introduce small human observable delay
		for(uint32_t volatile i=0; i < 300000; i++);

		pPortDOutReg->pin_12 = 0;

		for(uint32_t volatile i=0; i < 300000; i++);

	}
}
