/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"

int main(void) {

	RCC_AHB1ENR_t volatile *const pClkCtrlReg = ADDR_REG_AHB1ENR;
	GPIOx_MODER volatile *const pPortDModeReg = ADDR_REG_GPIOD_MODE;
	GPIOx_ODR volatile *const pPortDOutReg = ADDR_REG_GPIOD_OD;

	pClkCtrlReg->gpiod_en = CLOCK_ENABLE;
	pPortDModeReg->pin_12 = MODE_CONF_OUTPUT;

	for(;;) {
		pPortDOutReg->pin_12 = LED_ON;

		// introduce small human observable delay
		for(uint32_t volatile i=0; i < DELAY_COUNT; i++);

		pPortDOutReg->pin_12 = LED_OFF;

		for(uint32_t volatile i=0; i < DELAY_COUNT; i++);

	}
}
