/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void) {
	 char a1 = 'A';
	    char a2 = 'p';
	    char a3 = 'p';
	    char a4 = 'l';
	    char a5 = 'e';
	    char a6 = ':';
	    char a7 = ')';

	    printf("Address of variable a1 = %p\n", &a1);
	    printf("Address of variable a1 = %p\n", &a2);
	    printf("Address of variable a1 = %p\n", &a3);
	    printf("Address of variable a1 = %p\n", &a4);
	    printf("Address of variable a1 = %p\n", &a5);
	    printf("Address of variable a1 = %p\n", &a6);
	    printf("Address of variable a1 = %p\n", &a7);
}
