/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


int main(void)
{
	int val1 = 50;
	int val2 = 30;

	__asm volatile("MOV R0,%0": :"r"(val1));
	__asm volatile("MOV R1,%0": :"r"(val2));

	__asm volatile ("ADD R0,R0,R1");
	__asm volatile ("STR R0,R2");

	for(;;);
}
