/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pClkCtrlreg = (uint32_t *) 0x40023830;
	uint32_t *pPortDModeReg = (uint32_t *) 0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t *) 0x40020C14;
	uint32_t *pPortAModeReg = (uint32_t *) 0x40020000;
	volatile uint32_t const *const pPortAInReg = (uint32_t const *const) 0x40020010;

	//1. Enable the clock for GPIO peripheral in the AHB1ENR
	// Enables GPIOA and GPIOD
	*pClkCtrlreg |= 9;

	//2. Configure the mode of the IO pin as output
	//a. Clear the 24th and 25th bit positions
	*pPortDModeReg &= ~(3 << 24);
	//b. make the 24th bit position as 1 (SET)
	*pPortDModeReg |= 1 << 24;

	//3. Configure the mode of the IO as input
	*pPortAModeReg &= ~3;

	for(;;) {

		if(*pPortAInReg & 0x1) {
			*pPortDOutReg |= 1 << 12;
		} else {
			*pPortDOutReg &= ~(1 << 12);
		}
		for(uint32_t i=0; i < 1000; i++);
	}
}
