/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>

#define ALIAS_BASE 0x22000000U
#define BITBAND_BASE 0x20000000

int main(void)
{
	uint8_t *ptr = (uint8_t*)0x20002000;

	*ptr = 0xff;

	// normal method
	// clearing the 7th bit position
	*ptr &= ~( 1 << 7);

	*ptr = 0xff;

	// bit band method
	uint8_t* alias_addr = (uint8_t*) (ALIAS_BASE + (32 * (0x200002000 - BITBAND_BASE)) + 7 * 4);

	// clearing 7t bit of address 0x20000200
	*alias_addr = 0;

	for(;;);
}
