/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

void generate_interrupt();
void change_access_level_unpriv();

int main(void)
{
	printf("In thread mode : before interrupt\n");

	change_access_level_unpriv();

	generate_interrupt();

	printf("In thread mode : after interrupt\n");

	for(;;);
}

void generate_interrupt() {
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= ( 1 << 3);

	//generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);
}

void change_access_level_unpriv() {
	__asm volatile ("MRS R0,CONTROL");
	__asm volatile ("ORR R0,R0,#0x01");
	__asm volatile ("MSR CONTROL,R0");
}


void RTC_WKUP_IRQHandler(void) {
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void) {
	printf("Hard fault detected");
	while(1);
}

